### Songs INDEX

GET http://localhost:3000/songs.json


### Songs SHOW

GET http://localhost:3000/songs/1.json

### Songs CREATE
POST http://localhost:3000/songs.json
Content-Type: application/json

{
"title": "My Feelings For You",
"album": "My Feelings For You",
"artist": "Avicii",
"year": 2010
}

### Songs UPDATE
PATCH http://localhost:3000/songs/5.json
Content-Type: application/json

{
  "artist": "Dillon Francis, NGHTMRE"
}

### Songs DELETE

DELETE http://localhost:3000/songs/3.json
